package com.github.listemanuel95.flexiblesearch.utils

internal const val SELECT = "SELECT"
internal const val DISTINCT = "DISTINCT"
internal const val FROM = "FROM"
internal const val AS = "AS"
internal const val ON = "ON"
internal const val PK = "PK"
internal const val WHERE = "WHERE"
internal const val JOIN = "JOIN"
internal const val LEFT = "LEFT"
internal const val OUTER = "OUTER"
internal const val RIGHT = "RIGHT"
internal const val ORDER_BY = "ORDER BY"
internal const val GROUP_BY = "GROUP BY"
internal const val COUNT = "COUNT"
internal const val MIN = "MIN"
internal const val MAX = "MAX"
internal const val AVG = "AVG"
internal const val SUM = "SUM"
internal const val EXISTS = "EXISTS"
internal const val HAVING = "HAVING"
internal const val UPPER = "UPPER"
internal const val AND = "AND"
internal const val OR = "OR"
internal const val UNION = "UNION"
internal const val UNION_ALL = "UNION ALL"
internal const val TYPECODE_FIELD = "_TYPECODE"
